version: "3"

services:
  couchbase:
    container_name: couchbase-db
    image: couchbase:latest
    ports:
      - target: "8091-8096:8091-8096"
        published: "8091-8096:8091-8096"
        mode: host
      - target: "11210-11211:11210-11211"
        published: "11210-11211:11210-11211"
        mode: host
    volumes:
      - ./couchbase:/opt/couchbase/var

  sync-gateway:
    container_name: couchbase-sync-gateway
    depends_on:
      - server
    entrypoint: ["/config.sh"]
    image: couchbase/sync-gateway:2.7.0-community
    ports:
      - "4984:4984"
      - "4985:4985"
    volumes:
      - ./docker/sync-gateway/config.json:/etc/sync_gateway/template.json
      - ./docker/sync-gateway/config.sh:/config.sh
      - ./docker/sync-gateway/sync-functions/active.js:/etc/sync_gateway/sync_functions/active.js
