version: "3"

services:
  couchbase:
    container_name: couchbase-db
    image: couchbase:latest
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - ./couchbase:/opt/couchbase/var
    networks:
      - couchbase

  sync-gateway:
    container_name: couchbase-sync-gateway
    depends_on:
      - server
    entrypoint: ["/config.sh"]
    image: couchbase/sync-gateway:2.7.0-community
    ports:
      - "4984:4984"
      - "4985:4985"
    volumes:
      - ./couchbase-config/sync-gateway-config.json:/etc/sync_gateway/config.json
    networks:
      - couchbase

networks:
  couchbase:
    driver: bridge
