version: "3"

services:
  couchbase:
    container_name: couchbase-db
    image: couchbase:community-7.0.0
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - ./couchbase:/opt/couchbase/var
    networks:
      - couchbase

  sync-gateway:
    container_name: couchbase-sync-gateway
    depends_on:
      - couchbase
    image: couchbase/sync-gateway:2.8.2-community
    ports:
      - 4984:4984
      - 4985:4985
    volumes:
      - ./couchbase-config/sync-gateway-config.json:/etc/sync_gateway/config.json
    networks:
      - couchbase

networks:
  couchbase:
    driver: bridge
